In [1]:
# Student data - list of dictionaries
# Each student has a name, grade, and age
students = [
    {'name': 'Ali',  'grade': 85, 'age': 20},
    {'name': 'Sara', 'grade': 92, 'age': 22},
    {'name': 'John', 'grade': 78, 'age': 19},
    {'name': 'Lena', 'grade': 88, 'age': 21},
]

In [2]:
# Task 1: Sort by grade - lowest grade first (ascending order)
sorted_by_grade_low = sorted(students, key=lambda s: s['grade'])
print('Task 1 - Grade Low to High:')
for s in sorted_by_grade_low:
    print(s)

Task 1 - Grade Low to High:
{'name': 'John', 'grade': 78, 'age': 19}
{'name': 'Ali', 'grade': 85, 'age': 20}
{'name': 'Lena', 'grade': 88, 'age': 21}
{'name': 'Sara', 'grade': 92, 'age': 22}


In [3]:
# Task 2: Sort by grade - highest grade first (descending order)
# reverse=True flips the order from high to low
sorted_by_grade_high = sorted(students, key=lambda s: s['grade'], reverse=True)
print('Task 2 - Grade High to Low:')
for s in sorted_by_grade_high:
    print(s)

Task 2 - Grade High to Low:
{'name': 'Sara', 'grade': 92, 'age': 22}
{'name': 'Lena', 'grade': 88, 'age': 21}
{'name': 'Ali', 'grade': 85, 'age': 20}
{'name': 'John', 'grade': 78, 'age': 19}


In [4]:
# Task 3: Sort by age - youngest student first (ascending order)
sorted_by_age = sorted(students, key=lambda s: s['age'])
print('Task 3 - Youngest First:')
for s in sorted_by_age:
    print(s)

Task 3 - Youngest First:
{'name': 'John', 'grade': 78, 'age': 19}
{'name': 'Ali', 'grade': 85, 'age': 20}
{'name': 'Lena', 'grade': 88, 'age': 21}
{'name': 'Sara', 'grade': 92, 'age': 22}


In [5]:
# Task 4: Sort by name alphabetically (A to Z)
sorted_by_name = sorted(students, key=lambda s: s['name'])
print('Task 4 - Name A to Z:')
for s in sorted_by_name:
    print(s)

Task 4 - Name A to Z:
{'name': 'Ali', 'grade': 85, 'age': 20}
{'name': 'John', 'grade': 78, 'age': 19}
{'name': 'Lena', 'grade': 88, 'age': 21}
{'name': 'Sara', 'grade': 92, 'age': 22}


In [6]:
# Task 5: Sort by highest grade first
# If two students have the same grade, sort them by name (A to Z)
# Using a tuple in lambda: first sort by grade (descending), then by name (ascending)
sorted_by_grade_then_name = sorted(students, key=lambda s: (-s['grade'], s['name']))
print('Task 5 - Highest Grade First, then Name A-Z if same grade:')
for s in sorted_by_grade_then_name:
    print(s)

Task 5 - Highest Grade First, then Name A-Z if same grade:
{'name': 'Sara', 'grade': 92, 'age': 22}
{'name': 'Lena', 'grade': 88, 'age': 21}
{'name': 'Ali', 'grade': 85, 'age': 20}
{'name': 'John', 'grade': 78, 'age': 19}


In [7]:
# os jo h file ka path batata h hame.
import os
print(os.getcwd())

D:\python-projects\Python-Projects\muet.class


In [8]:
# current directory bata raha single . se or double dote se previous directory. 
import os 
print(os.listdir("."))

['age_calculator.py', 'grades.py', 'grades.txt', 'list_files.py', 'main.py', 'math_helpers.py', 'muet-class.ipynb', 'quiz.py', 'students.csv', '__pycache__']


In [9]:
import requests
response = requests.get("https://api.github.com")
print(response.status_code)


200


In [10]:
import csv
data = [['name', 'age', 'grade', 'city', 'country'],
        ['aqsa', 20, 'A', 'karachi', 'pakistan'],
        ['fasih', 25, 'A', 'hyd', 'pakistan']
        ]
with open('students.csv', 'w', newline='') as file:
        writer = csv.writer(file)
        writer.writerows(data)

with open('students.csv', 'r') as file:
        reader = csv.reader(file)
        for row in reader:
                print(row)


['name', 'age', 'grade', 'city', 'country']
['aqsa', '20', 'A', 'karachi', 'pakistan']
['fasih', '25', 'A', 'hyd', 'pakistan']


In [11]:
import numpy as np

# 1d array from a list
marks = np.array([99, 85, 77, 98])
print(marks)

[99 85 77 98]


In [12]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Shape:", arr.shape)    # kitni rows/columns hain
print("Ndim:", arr.ndim)      # kitne dimensions hain
print("Size:", arr.size)      # total elements kitne hain
print("Dtype:", arr.dtype)    # data type kya hai


Array: [10 20 30 40 50]
Shape: (5,)
Ndim: 1
Size: 5
Dtype: int64


In [13]:
import numpy as np

arr1 = np.arange(1, 26)
arr2 = np.arange(1, 16)

print("Array 1:", arr1)
print("Array 1 Size:", arr1.size)
print("Array 2:", arr2)
print("Array 2 Size:", arr2.size)

result = np.concatenate((arr1, arr2))
print("Dono array add ke baad:", result)
print("Result ka size:", result.size)


Array 1: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
Array 1 Size: 25
Array 2: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Array 2 Size: 15
Dono array add ke baad: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Result ka size: 40


In [14]:
import numpy as np

# 2D array - 2 dimensions
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("2D Array:")
print(arr_2d)
print("Shape:", arr_2d.shape)
print("Ndim:", arr_2d.ndim)
print("Size:", arr_2d.size)
print("Dtype:", arr_2d.dtype)


2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Ndim: 2
Size: 9
Dtype: int64
